# Generated by Django 4.0.10 on 2023-03-02 10:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_userprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('blog_content', models.CharField(max_length=1028, null=True)),
                ('media_url', models.CharField(max_length=1028, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 3, 2, 10, 30, 37, 320968))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
    ]
