# Generated by Django 4.0.10 on 2023-03-02 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apis', '0003_remove_blog_is_deleted_alter_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 17, 54, 22, 985604)),
        ),
    ]
