# Generated by Django 4.0.10 on 2023-03-03 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apis', '0004_alter_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 11, 53, 48, 346185)),
        ),
    ]
