# Generated by Django 4.0.10 on 2023-03-03 21:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apis', '0005_alter_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 21, 9, 56, 250515, tzinfo=utc)),
        ),
    ]
