# Generated by Django 4.0.10 on 2023-03-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16, unique=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('dob', models.DateField(null=True)),
                ('address', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
