# Generated by Django 4.0.10 on 2023-03-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_user',
            field=models.BooleanField(default=True),
        ),
    ]
